### ISSUE TITLE
Extension and CSS not working

### ISSUE THREAD

**Issue by Explosion-Scratch** [notionblog/NotionThemes#3]
The extension just isn't working. The options page lets me select a theme, then I reload notion, and... Nothing. No idea what's going on. I also tried using stylus and testing some of the themes from the extension (I looked through the code and found the CSS), this CSS does absolutely nothing:

```css
:root {
  --bg: #161b22;
  --bg-light: #161b22;
  --bg-lighter: #0d1117;
  --fg: #ffffffe6;
  --fg-light: #8b949e;
  --fg-lighter: var(--fg-light);
  --main: #1f6feb;
  --hover: #30363d;
  --border: #30363d;
  --selection: #2eaadc40;
  --gray: #838789;
  --brown: #894500;
  --orange: #e38c00;
  --yellow: #f1e05a;
  --green: #238636;
  --blue: #58a6ff;
  --purple: #a371f7;
  --pink: #e255a1;
  --red: #e34c26;
  --bg-gray: #7e80814d;
  --bg-brown: #6a2b00ad;
  --bg-orange: #ff9900a6;
  --bg-yellow: #c7b133b0;
  --bg-green: #52c54d63;
  --bg-blue: #005a9285;
  --bg-purple: #5a319459;
  --bg-pink: #ff50ad85;
  --bg-red: #7a14149f;
}
```

So no idea why it's not working =|

Also, user agent:
```
Mozilla/5.0 (X11; CrOS x86_64 14440.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.100.4807.0 Safari/537.36
```
